name: Trend Tech Media Poster

on:
  schedule:
    - cron: '0 7 * * *' # بتوقيت جرينتش (9 صباحاً مصر)
  workflow_dispatch: # عشان تقدر تشغله يدوي في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests feedparser

      - name: Run Image Generator
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
        run: python image_poster.py
